' Developer Express Code Central Example:
' How to style GridControl's group summary items via the GroupColumnSummaryItemTemplate property
' 
' When group summary items are aligned by columns, it is necessary to use the
' TableView's GroupColumnSummaryItemTemplate property to style GridControl group
' summary items. The main idea of this approach is to define a custom ItemsControl
' inside the GroupColumnSummaryItemTemplate, bind its ItemsSource property to the
' collection of group summaries and show summary items as child ItemsControl
' elements. To customize summaries you can use ItemsControl properties, for
' instance, ItemTemplateSelector.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4998

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
